.TH ii-go 1  "March 12, 2023" "version 0.1.0" "II-GO"
.SH NAME
ii-go \- is idec node and tools
.SH SYNOPSIS
.B ii-tool, ii-node, ii-gemini
.SH DESCRIPTION
Easy setup and make your own ii/idec node.
.PP
.B ii-tool
\- can be used to fetch messages from another node and maintaince database.
.PP
.B ii-node
\- runing idec node with web interface 
.PP
.B ii-gemini
\- generate gemini data
.SH SEE ALSO
ii-tool(1), ii-node(1), ii-gemini(1)

.SH HISTORY
needed!!!
https://github.com/idec-net/new-docs/blob/master/main.md
.SH AUTHOR
hugeping ( gl00my (at) mail.ru )
