.TH ii-tool 1  "March 12, 2023" "version 0.1.0" "II-GO"
.SH NAME
ii-gemini - generate gemini data
.SH SYNOPSIS
.B ii-gemini
[options] command [arguments]
.SH DESCRIPTION
Generate gemini data from idec db.
.SH OPTIONS
.TP
-data <path> gemini
generate gemini data
.TP
-db=<path>
database path
.SH EXAMPLES

.SH AUTHOR
hugeping ( gl00my (at) mail.ru )
.SH SEE ALSO
ii-tool(1), ii-node(1), ii-go(1)